name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Publish to GitHub Packages
      working-directory: springboot-utils
      run: mvn deploy --settings ${{ github.workspace }}/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build complete
      run: echo "Paquete publicado en GitHub Packages"

